
- name: download the cert-manager manifest
  ansible.builtin.get_url:
    url: "{{ settings.rancher_node.cert_manager_manifest_url }}"
    dest: /home/vagrant/cert-manager.yaml
    mode: '0664'

- name: Apply cert-manager.yaml manifest to the cluster
  ansible.builtin.shell: |
    KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl apply -f /home/vagrant/cert-manager.yaml
  register: apply_cert_manager_manifest_result

- name: debug apply cert manager manifest result
  ansible.builtin.debug:
    msg: "{{ apply_cert_manager_manifest_result }}"
  ignore_errors: true

# TODO: Figure out why the community plugin for helm is simply not working right...

# - name: install python3-pip
#   ansible.builtin.apt:
#     name: python3-pip
#     state: present
#     update_cache: yes

# - name: pip3 install pip upgrade
#   ansible.builtin.pip:
#     name: pip
#     extra_args: --upgrade
#     executable: pip3

# - name: pip install PyYAML
#   ansible.builtin.pip:
#     name: PyYAML
#     state: present

# - name: Add jetstack chart repo
#   kubernetes.core.helm_repository:
#     binary_path: /usr/local/bin/helm
#     repo_url: "https://charts.jetstack.io"
#     kubeconfig: /etc/rancher/k3s/k3s.yaml
#     name: jetstack

# - name: update helm repo cache
#   kubernetes.core.helm_repository:
#     binary_path: /usr/local/bin/helm
#     kubeconfig: /etc/rancher/k3s/k3s.yaml
#     update_cache: yes

# - name: deploy cert-manager helm chart
#   kubernetes.core.helm:
#     binary_path: /usr/local/bin/helm
#     chart_ref: jetstack/cert-manager
#     release_namespace: cert-manager
#     create_namespace: true
#     kubeconfig: /etc/rancher/k3s/k3s.yaml

# TODO: ideally, not use this, use the ansible plugin... not sure why it's not working right...

- name: helm repo add jetstack
  ansible.builtin.shell: |
    KUBECONFIG=/etc/rancher/k3s/k3s.yaml helm repo add jetstack https://charts.jetstack.io
    KUBECONFIG=/etc/rancher/k3s/k3s.yaml helm repo update
    KUBECONFIG=/etc/rancher/k3s/k3s.yaml helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version {{ settings.rancher_node.cert_manager_version_to_install }}
  register: helm_repo_add_jetstack_result

- name: debug helm repo add jetstack result
  ansible.builtin.debug:
    msg: "{{ helm_repo_add_jetstack_result }}"
  ignore_errors: true

- name: wait for cert-manager to be ready
  ansible.builtin.shell: |
    KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl wait --for=condition=available --timeout=600s deployment/cert-manager-webhook -n cert-manager
  register: wait_for_cert_manager_result

- name: debug wait for cert manager result
  ansible.builtin.debug:
    msg: "{{ wait_for_cert_manager_result }}"
  ignore_errors: true