---
- name: parse Harvester media download URL
  set_fact:
    harvester_download_url_facts: "{{ harvester_media_url | urlsplit }}"

- name: copy Harvester media from local directory
  copy:
    src: "{{ harvester_download_url_facts['path'] }}"
    dest: "{{ settings['kea_server']['storage']['caddy_fileserver']['mount_point'] }}/{{ settings['kea_server']['caddy_fileserver_config']['harvester_folder_name'] }}/{{ media_filename }}"
  when: harvester_download_url_facts['scheme']|lower == 'file'

- name: download Harvester media
  get_url:
    url: "{{ harvester_media_url }}"
    dest: "{{ settings['kea_server']['storage']['caddy_fileserver']['mount_point'] }}/{{ settings['kea_server']['caddy_fileserver_config']['harvester_folder_name'] }}/{{ media_filename }}"
  when: harvester_download_url_facts['scheme']|lower != 'file'
